apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windows-install
  namespace: openshift-gitops
spec:
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  project: default
  source:
    path: win2k19
    repoURL: https://github.com/cwilkers/kubevirt-gitops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
