apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: openshift-gitops
spec:
  destination:
    namespace:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubevirt
    repoURL: https://github.com/RHsyseng/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=false
