apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vms
  namespace: openshift-gitops
spec:
  destination:
    namespace: kubevirt-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vms
    repoURL: https://github.com/cwilkers/kubevirt-gitops
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=false
