apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdi
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: cdi
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cdi
    repoURL: https://github.com/cwilkers/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
