apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: kubevirt
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubevirt
    repoURL: https://github.com/cwilkers/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
